export const categories = [
  { id: 1, label: "For Sale", value: "for sale" },
  { id: 2, label: "Jobs", value: "jobs" },
  { id: 3, label: "Pets", value: "pets" },
  { id: 4, label: "Community", value: "community" },
  { id: 5, label: "Real Estate", value: "real estate" },
  { id: 6, label: "Free Stuff", value: "free stuff" },
  { id: 7, label: "Services", value: "services" },
];

export const conditions = [
  { id: 1, label: "New", value: "new" },
  { id: 2, label: "Used", value: "used" },
];

export const deliveryMethods = [
  { id: 1, label: "Shipping", value: "shipping" },
  { id: 2, label: "Pick Up", value: "pick up" },
];

export const locations = [
  { id: 1, label: "Alabama", value: "al" },
  { id: 2, label: "Alaska", value: "ak" },
  { id: 3, label: "Arizona", value: "az" },
  { id: 4, label: "Arkansas", value: "ar" },
  { id: 5, label: "California", value: "ca" },
  { id: 6, label: "Colorado", value: "co" },
  { id: 7, label: "Connecticut", value: "ct" },
  { id: 8, label: "Delaware", value: "de" },
  { id: 9, label: "Florida", value: "fl" },
  { id: 10, label: "Georgia", value: "ga" },
  { id: 11, label: "Hawaii", value: "hi" },
  { id: 12, label: "Idaho", value: "id" },
  { id: 13, label: "Illinois", value: "il" },
  { id: 14, label: "Indiana", value: "in" },
  { id: 15, label: "Iowa", value: "ia" },
  { id: 16, label: "Kansas", value: "ks" },
  { id: 17, label: "Kentucky", value: "ky" },
  { id: 18, label: "Louisiana", value: "la" },
  { id: 19, label: "Maine", value: "me" },
  { id: 20, label: "Maryland", value: "md" },
  { id: 21, label: "Massachusetts", value: "ma" },
  { id: 22, label: "Michigan", value: "mi" },
  { id: 23, label: "Minnesota", value: "mn" },
  { id: 24, label: "Mississippi", value: "ms" },
  { id: 25, label: "Missouri", value: "mo" },
  { id: 26, label: "Montana", value: "mt" },
  { id: 27, label: "Nebraska", value: "ne" },
  { id: 28, label: "Nevada", value: "nv" },
  { id: 29, label: "New Hampshire", value: "nh" },
  { id: 30, label: "New Jersey", value: "nj" },
  { id: 31, label: "New Mexico", value: "nm" },
  { id: 32, label: "New York", value: "ny" },
  { id: 33, label: "North Carolina", value: "nc" },
  { id: 34, label: "North Dakota", value: "nd" },
  { id: 35, label: "Ohio", value: "oh" },
  { id: 36, label: "Oklahoma", value: "ok" },
  { id: 37, label: "Oregon", value: "or" },
  { id: 38, label: "Pennsylvania", value: "pa" },
  { id: 39, label: "Rhode Island", value: "ri" },
  { id: 40, label: "South Carolina", value: "sc" },
  { id: 41, label: "South Dakota", value: "sd" },
  { id: 42, label: "Tennessee", value: "tn" },
  { id: 43, label: "Texas", value: "tx" },
  { id: 44, label: "Utah", value: "ut" },
  { id: 45, label: "Vermont", value: "vt" },
  { id: 46, label: "Virginia", value: "va" },
  { id: 47, label: "Washington", value: "wa" },
  { id: 48, label: "West Virginia", value: "wv" },
  { id: 49, label: "Wisconsin", value: "wi" },
  { id: 50, label: "Wyoming", value: "wy" },
];
export const stateData = [
  { name: "Alabama", value: "al" },
  { name: "Alaska", value: "ak" },
  { name: "Arizona", value: "az" },
  { name: "Arkansas", value: "ar" },
  { name: "California", value: "ca" },
  { name: "Colorado", value: "co" },
  { name: "Connecticut", value: "ct" },
  { name: "Delaware", value: "de" },
  { name: "Florida", value: "fl" },
  { name: "Georgia", value: "ga" },
  { name: "Hawaii", value: "hi" },
  { name: "Idaho", value: "id" },
  { name: "Illinois", value: "il" },
  { name: "Indiana", value: "in" },
  { name: "Iowa", value: "ia" },
  { name: "Kansas", value: "ks" },
  { name: "Kentucky", value: "ky" },
  { name: "Louisiana", value: "la" },
  { name: "Maine", value: "me" },
  { name: "Maryland", value: "md" },
  { name: "Massachusetts", value: "ma" },
  { name: "Michigan", value: "mi" },
  { name: "Minnesota", value: "mn" },
  { name: "Mississippi", value: "ms" },
  { name: "Missouri", value: "mo" },
  { name: "Montana", value: "mt" },
  { name: "Nebraska", value: "ne" },
  { name: "Nevada", value: "nv" },
  { name: "New Hampshire", value: "nh" },
  { name: "New Jersey", value: "nj" },
  { name: "New Mexico", value: "nm" },
  { name: "New York", value: "ny" },
  { name: "North Carolina", value: "nc" },
  { name: "North Dakota", value: "nd" },
  { name: "Ohio", value: "oh" },
  { name: "Oklahoma", value: "ok" },
  { name: "Oregon", value: "or" },
  { name: "Pennsylvania", value: "pa" },
  { name: "Rhode Island", value: "ri" },
  { name: "South Carolina", value: "sc" },
  { name: "South Dakota", value: "sd" },
  { name: "Tennessee", value: "tn" },
  { name: "Texas", value: "tx" },
  { name: "Utah", value: "ut" },
  { name: "Vermont", value: "vt" },
  { name: "Virginia", value: "va" },
  { name: "Washington", value: "wa" },
  { name: "West Virginia", value: "wv" },
  { name: "Wisconsin", value: "wi" },
  { name: "Wyoming", value: "wy" },
];

export const mainCategories = [
  { name: "For Sale", value: "for_sale" },
  { name: "Jobs", value: "jobs" },
  { name: "Pets", value: "pets" },
  { name: "Community", value: "community" },
  { name: "Real Estate", value: "real_estate" },
  { name: "Free Stuff", value: "free_stuff" },
  { name: "Services", value: "services" },
];

export const subCategories = {
  for_sale: [
    { name: "General Items", value: "general_items" },
    { name: "Clothing & Accessories", value: "clothing_accessories" },
    { name: "Cars & Vehicles", value: "cars_vehicles" },
  ],
  jobs: [
    { name: "Full-Time/Remote", value: "full_time_remote" },
    { name: "Advertisement and Hire", value: "advertisement_hire" },
    { name: "Freelance", value: "freelance" },
  ],
  pets: [
    { name: "Pets for Sale", value: "pets_for_sale" },
    { name: "Pet Services", value: "pet_services" },
  ],
  community: [
    { name: "Events", value: "events" },
    { name: "Activities", value: "activities" },
    { name: "Missed Connections", value: "missed_connections" },
    { name: "Lost + Found", value: "lost_found" },
  ],
  real_estate: [
    { name: "Rentals", value: "rentals" },
    { name: "For Sale", value: "real_estate_for_sale" },
  ],
  free_stuff: [
    { name: "Free to Collect", value: "free_to_collect" },
    { name: "Giveaways", value: "giveaways" },
  ],
  services: [
    { name: "Cleaning Services", value: "cleaning_services" },
    { name: "Moving & Transportation", value: "moving_transportation" },
  ],
};
